config/routes.rb
Rails.application.routes.draw do
 
  
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
}
 
  resources :users, :only => [:show]
  post 'comments/:id' =>"comments#create",as:'comment'
  delete 'comments/:post_id/:id'=>"comments#destroy",as:'destroy_comment'
  post 'relationship/:id'=>"relationships#create",as:'create_relationship'
  delete'relationship/:id'=>"relationships#destroy",as:'destroy_relationship'
  root 'home#top'
  post "likes/:post_id/create"=>"likes#create",as:'create_like'
  post "likes/:post_id/destroy"=>"likes#destroy",as:'destroy_like'
  get 'posts'=>'posts#index'
  get "posts/new"=>"posts#new"
  post "posts"=>"posts#create"
  get "posts/:id"=>"posts#show",as:'post'
  patch 'posts/:id' => 'posts#update'
  delete 'posts/:id' => 'posts#destroy' 
  get 'posts/:id/edit' => 'posts#edit', as:'edit_post'
  post 'posts/:id/done'=>'posts#done',as:'done_post'

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  validates :body, presence: true,length: { maximum: 75 }    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  
  require "date"


  def index
    @posts=Post.all.order(id: "DESC")
  end

  def new
    @post=Post.new
    @user = current_user
    @followings=@user.followings
    @followers=@user.followers
  end

  def create
    @user = current_user
    @followings=@user.followings
    @followers=@user.followers
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:notice]="新しいチャレンジが登録されました！"
      redirect_to :action => "index"
    else
      render("posts/new")
    end
  end

  def show
    @post=Post.find(params[:id])
    @comments = @post.comments.order(id: "DESC")
    @comment = @post.comments.build
  end 

  def edit
    @user = current_user
    @followings=@user.followings
    @followers=@user.followers
    @post = Post.find(params[:id])
  end

  def update
    @user = current_user
    @post = Post.find(params[:id])
    @followings=@user.followings
    @followers=@user.followers
    if @post.update(post_params)
      flash[:notice]="編集されました"
      redirect_to :action => "show", :id => @post.id
    else
      render("posts/edit")
    end
  end

  def destroy
    flash[:notice]="削除されました"
    Post.find(params[:id]).destroy
    redirect_to action: :index
  end

  def done
    post=Post.find(params[:id])
    if post.date==Date.today
      redirect_to :action =>"show", :id => post.id
      flash[:notice]="更新は１日一回です"
    else
      post.date=Date.today
      post.increment(:day,1)
      post.save
      flash[:notice]="更新しました"
      redirect_back(fallback_location: root_path)
    end
  end


  private
  def post_params
    params.require(:post).permit(:body,:day,:date)
  end



end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="main back">
 <div class="post-new">
    <div class="user-show-header">
        <div class="name-follow">
          <h2><%=@user.name%></h2>
          <% unless current_user == @user %>
            <% if current_user.following?(@user) %>
              <%=link_to "Unfollow", destroy_relationship_path(@user.id),method: :delete%>
          <% else %>
              <%=link_to "Follow", create_relationship_path(@user.id),method: :post%>
            <% end %>
          <% end %>
        </div>
      <p>フォロー中 <%=@followings.count%></p>
      <p>フォロワー <%=@followers.count%></p>
    </div>
 <div class="post-new-container">
  <h1>チャレンジを編集する</h1>
  <%= form_for @post do |f| %>
    <%@post.errors.full_messages.each do |m|%>
      <div class="error">
        <%= m %>
      </div>
    <%end%>
  <div class="field">
    <p>チャレンジ:</p>
    <%= f.text_field :body, :size => 140 %>
  </div>
  <i class="fas fa-arrow-right"></i>
  <%= f.submit "編集" %>
  <% end %>
<%= link_to "チャレンジ一覧に戻る", posts_path%>
  </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="main back"> 
  <div class="tweets-container">
    <div class="index-new">
    <i class="fas fa-arrow-right"></i>
    <%= link_to "新規投稿へ", posts_new_path %>
    </div>
  <% @posts.each do |t| %>
    <div class="tweet">
        <%=link_to user_path(t.user.id) do%>
        <h2><%=t.user.name%></h2>
        <%end%>
        <p><%= t.body %></p>
        <div class="day">
        <p><%=t.day%>日</p>
        
        <div class="day-bar">
          <%for i in 1..10%>
            <%if i<=t.day%>
              <i  class="fas fa-circle step1"> </i>
            <%else%>
              <i  class="fas fa-circle step2"></i>
            <%end%>
            <%if i!=10%>
              <i class="fas fa-angle-right bar-arrow"></i>
            <%end%>  
          <%end%>
        </div> 
        <% if t.user_id == current_user.id%>
        <% if t.date!=Date.today%>
        <p class="done"><%= link_to "更新",done_post_path(t.id), method: :post%> </p>
        <%end%>
        <%end%>
        </div>
        <div class="post-menu">
          <p>最終更新日<%= t.date%></p>
          <%=link_to "詳細", post_path(t.id)%> 
          <% if t.user_id == current_user.id%>
          <%= link_to "編集する", edit_post_path(t.id) %>
          <%= link_to "削除する", post_path(t.id), method: :delete %>
          <%end%>
          <div class="like">  
          <%if Like.find_by(user_id:current_user.id,post_id:t.id)%>
            <%= link_to destroy_like_path(t.id), method: :post do%> 
            <i class="fas fa-heart"></i>
            <%end%>
          <%else%>
            <%= link_to create_like_path(t.id), method: :post do%> 
            <i class="far fa-heart"></i>
            <%end%>
          <%end%>
          <p><%=Like.where(post_id:t.id).count%></p>
          </div>      
        </div>
      </div>
  <% end %>
</div>
</div>

app/views/posts/new.html.erb
<div class="main back">
 <div class="post-new">
    <div class="user-show-header">
        <div class="name-follow">
          <h2><%=@user.name%></h2>
          <% unless current_user == @user %>
            <% if current_user.following?(@user) %>
              <%=link_to "Unfollow", destroy_relationship_path(@user.id),method: :delete%>
          <% else %>
              <%=link_to "Follow", create_relationship_path(@user.id),method: :post%>
            <% end %>
          <% end %>
        </div>
      <p>フォロー中 <%=@followings.count%></p>
      <p>フォロワー <%=@followers.count%></p>
    </div>
 <div class="post-new-container">
  <h1>新しいチャレンジを始める</h1>
  <%= form_for @post do |f| %>
    <%@post.errors.full_messages.each do |m|%>
      <div class="error">
        <%= m %>
      </div>
    <%end%>
  <div class="field">
    <p>チャレンジ:</p>
    <%= f.text_field :body, :size => 140 %>
  </div>
  <i class="fas fa-arrow-right"></i>
  <%= f.submit "スタート" %>
  <% end %>
<%= link_to "チャレンジ一覧に戻る", posts_path%>
  </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="main back">
  <div class="post-show">
    <h1>チャレンジ詳細</h1>
    <div class="tweet post-show-content">
      <%=link_to user_path(@post.user.id) do%>
        <h2><%=@post.user.name%></h2>
      <%end%>
      <p><%= @post.body %></p>
      <div class="day">
        <p><%=@post.day%>日</p>
        <div class="day-bar">
          <%for i in 1..10%>
            <%if i<=@post.day%>
              <i  class="fas fa-circle step1"> </i>
            <%else%>
              <i  class="fas fa-circle step2"></i>
            <%end%>
            <%if i!=10%>
              <i class="fas fa-angle-right bar-arrow"></i>
            <%end%>  
          <%end%>
        </div> 
        <% if @post.user_id == current_user.id%>
        <% if @post.date!=Date.today%>
        <p class="done"><%= link_to "更新",done_post_path(@post.id), method: :post%> </p>
        <%end%>
        <%end%>
      </div>
      <div class="post-menu">
          <p>最終更新日<%= @post.date%></p>
          
          <% if @post.user_id == current_user.id%>
          <%= link_to "編集する", edit_post_path(@post.id) %>
          <%= link_to "削除する", post_path(@post.id), method: :delete %>
          <%end%>
          <div class="like">  
          <%if Like.find_by(user_id:current_user.id,post_id:@post.id)%>
            <%= link_to destroy_like_path(@post.id), method: :post do%> 
            <i class="fas fa-heart"></i>
            <%end%>
          <%else%>
            <%= link_to create_like_path(@post.id), method: :post do%> 
            <i class="far fa-heart"></i>
            <%end%>
          <%end%>
          <p><%=Like.where(post_id:@post.id).count%></p>
          </div>      
      </div>
    </div>
      <%= link_to "チャレンジ一覧に戻る", posts_path%>
        
        <div class="comment-wrapper">
          <h4>コメント <i class="far fa-comment"></i></h4>
          <div class="comment-new">
              <% if user_signed_in? %>
                <%= form_with(model: [@post, @comment],url:comment_path(@post.id) ,local: true) do |f| %>
                  <%= f.text_field :comment%>
                    <div class="comment-bottun">
                    <i class="fas fa-arrow-right"></i>
                    <%= f.submit "コメントする" %>
                    </div>
                <% end %>
              <% end %>
          </div>
          <% @comments.each do |c| %>
            <div class="comment-index">
               <%=link_to user_path(c.user.id) do%>
                <h2><%=c.user.name unless c.user.blank?%></h2>
                <%end%>

              <p><%= c.comment %></p>
            　<div class="comment-menu">
              <%= link_to "DELETE", destroy_comment_path(post_id: @post, id: c.id), method: :delete %>
              </div>
            </div>  
            
          <% end %>
          
          
        </div>
  </div>      
</div>